format = "[$all](italic)"

[directory]
truncation_length = 5
truncation_symbol = "â€¦/"
repo_root_style = "cyan bold italic"

[git_branch]
symbol = "Â±"
style = "purple bold italic"

[status]
disabled = false

[nodejs]
symbol = 'ğŸ¤– '

[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "
unknown_symbol = "ğŸ’€ "
empty_symbol = "ğŸª« "
