format = "[$all](italic)"

[directory]
format = '[%\(4~|%-1~/â€¦/%2~|%~\)]($style)[$read_only]($read_only_style) '

[git_branch]
symbol = "Â±"
style = "purple bold italic"

[status]
disabled = false

[nodejs]
symbol = 'ðŸ¤– '
