add_newline = false

[directory]
truncation_length = 5
truncation_symbol = "â€¦/"
repo_root_style = "cyan bold italic"

[git_branch]
symbol = "Â±"

[git_status]
format = '([\[](white bold)[$all_status$ahead_behind]($style)[\]](white bold)) '
ahead = "â†‘"
behind = "â†“"
conflicted = "[!](red)"
diverged = "â†•"
modified = '[!](bright-yellow bold)'
renamed = '[Â»](bright-yellow bold)'
staged = '[+](green bold)'
up_to_date = '[â‰¡](green bold)'

[status]
disabled = false

[nodejs]
symbol = 'ğŸ¤– '

[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "
unknown_symbol = "ğŸ’€ "
empty_symbol = "ğŸª« "
[[battery.display]]
threshold = 10
style = "bold red"
[[battery.display]]
threshold = 30
style = "bold yellow"
